[phases.setup]
nixPkgs = ["python311", "texlive.combined.scheme-basic", "pandoc"]

[phases.install]
cmds = ["pip install -r requirements.txt", "python -m spacy download en_core_web_sm"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"
